# Generated by Django 4.2.1 on 2023-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
    ]
